### ISSUE TITLE
Update AEP SDKs to include privacy manifest

### ISSUE THREAD

**Issue by CloudosaurusRex** [adobe/aepsdk-analytics-ios#103]
At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs will need to provide a privacy manifest.

It looks like the AEP SDKs will need to do this because, amongst others, they make use of `UserDefaults`, which is now considered a "required reason" API.

Is this update on the roadmap for the team? I appreciate that enforcement won't happen until Spring 2024 but I wanted to make contact so that we can plan our own app releases to take this into account.

For more info, see:
- [Describing data use in privacy manifests | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests) 
- [Describing use of required reason API | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) 
- [Get started with privacy manifests - WWDC23 - Videos - Apple Developer](https://developer.apple.com/videos/play/wwdc2023/10060/)

Thanks!

**Comment by nokiaowner** [comment]
Any update on this please? Deadline is approaching.

**Comment by isthisjoe** [comment]
+1

**Comment by praveek** [comment]
We are working on 5.x versions of all our iOS SDKs to address Privacy Manifest. I will update the release date soon.

**Comment by Deepak07527** [comment]
@praveek When you are releasing the 5.x versions as time is approaching.

**Comment by praveek** [comment]
We are working on releasing the 5.x SDKs in the latter half of March.

**Comment by cdhoffmann** [comment]
Hey everyone. [Here](https://developer.adobe.com/client-sdks/resources/privacy-manifest/) is our public doc on iOS 17 and Privacy Manifests. Thanks for your patience!

**Comment by praveek** [comment]
The 5.x SDKs have been released. Refer [our documentation](https://developer.adobe.com/client-sdks/home/release-notes/#march-20-2024) for more information on this release.
