### ISSUE TITLE
Swift Package Collection has invalid signature, cert expired back in Jan

### ISSUE THREAD

**Issue by funcJeff** [adobe/aepsdk-analytics-ios#118]
### Expected Behaviour

- When following directions at https://developer.adobe.com/client-sdks/resources/manage-spm-dependencies/
- Which references the Swift Package Collection definition at https://opensource.adobe.com/aepsdk-core-ios/swift/packages/aep.json
- We expect the package collection definition to be signed with a valid certificate
- We expect Xcode to use the package collection without problems.

### Actual Behaviour

- Instead the package collection definition has a certificate that expired in Jan 2024.
- And Xcode rejects the package collection.

### Reproduce Scenario (including but not limited to)

- Any valid example app.
- Using latest release version of Swift (5.10) and Xcode (15.3)

#### Steps to Reproduce

When this command is run:
```
swift package-collection add https://opensource.adobe.com/aepsdk-core-ios/swift/packages/aep.json
```

This is the output:
```
error: Failed to validate certificate chain [Certificate(version: X509v3, serialNumber: 24:77:dc:43:3f:c4:26:a2:d8:44:a7:3:f2:c4:14:e3, issuer: "C=US,O=Apple Inc.,OU=G3,CN=Apple Worldwide Developer Relations Certification Authority", subject: "C=US,O=Adobe Inc.,OU=JQ525L2MZD,CN=Swift Package Collection: Adobe Inc.,0.9.2342.19200300.100.1.1=JQ525L2MZD", notValidBefore: 2023-01-10 02:39:43 +0000, notValidAfter: 2024-01-10 02:39:42 +0000, publicKey: RSA2048.PublicKey, signature: RSA, extensions: [BasicConstraints(CA=FALSE), AuthorityKeyIdentifier(keyID: 9:fe:c0:15:90:f9:af:64:a:92:12:b9:26:28:63:c:97:ec:a7:b2), AuthorityInformationAccess((OCSP Server: URI("http://ocsp.apple.com/ocsp03-wwdrg319"))), Extension(oid: 2.5.29.32, critical: false, value: 277 bytes), ExtendedKeyUsage(codeSigning), SubjectKeyIdentifier(d7:db:3a:b:9a:88:27:6d:8:de:5e:74:6c:d0:1c:d6:d:87:62:a6), KeyUsage(digitalSignature), Extension(oid: 1.2.840.113635.100.6.1.35, critical: false, value: 2 bytes)])]: []
error: Default certificate policy: The certificate chain is invalid: invalidCertChain
warning: The signature of package collection [CollectionSource(type: PackageCollections.PackageCollectionsModel.CollectionSourceType.json, url: https://opensource.adobe.com/aepsdk-core-ios/swift/packages/aep.json, isTrusted: nil, skipSignatureCheck: false, absolutePath: nil)] is invalid: invalidCertChain
Error: The collection's signature is invalid. If you would like to continue please rerun command with '--skip-signature-check'.
```

#### Platform and Version

- Xcode 15.3
- Swift 5.10
- macOS 14.4.1

#### Sample Code that illustrates the problem

See recreation steps above.

#### Logs taken while reproducing problem

See recreation steps above.

**Comment by praveek** [comment]
@funcJeff Thanks for reporting this. I am working on refreshing the package collection and will update this issue once it is done.

**Comment by praveek** [comment]
@funcJeff The package collection is updated and should work as expected.
