### ISSUE TITLE
Versioning: SPM points to AEPCore 'main' branch

### ISSUE THREAD

**Issue by neyroja** [adobe/aepsdk-analytics-ios#43]
### Expected Behaviour

Adobe customer consuming AEPAnalytics consume stable dependencies.

### Actual Behaviour

AEPAnalytics package points to AEPCore 'main' branch

#### Sample Code that illustrates the problem

https://github.com/adobe/aepsdk-analytics-ios/blob/main/Package.swift
<img width="1240" alt="Screenshot 2021-06-23 at 15 48 32" src="https://user-images.githubusercontent.com/86352553/123108243-8b963200-d43a-11eb-85f8-96ff6f3ffaaf.png">

**Comment by praveek** [comment]
@neyroja Thanks for pointing it out. We will fix it with our next release.

**Comment by timsearle** [comment]
+1 on this!

Hey @praveek, any idea for timelines on when Core, Analytics and Target will have specific versions in the Package.swift? Hoping to migrate my codebase to these but feel uneasy having moving dependencies.

**Comment by praveek** [comment]
@timsearle @neyroja This has been fixed.

**Comment by tadija** [comment]
Hi @praveek, but this fix is not merged / released yet?

I still have to define Adobe packages like this:

```
.package(
    name: "AEPCore",
    url: "https://github.com/adobe/aepsdk-core-ios.git",
    from: "3.3.0"
),
.package(
    name: "AEPUserProfile",
    url: "https://github.com/adobe/aepsdk-userprofile-ios.git",
    from: "3.0.1"
),
/// - Note: can't make it work with explicit release (3.0.1), so we have to use "main" branch for now
.package(
    name: "AEPAnalytics",
    url: "https://github.com/adobe/aepsdk-analytics-ios.git",
    .branch("main")
),
```
