### ISSUE TITLE
Unable to generate xcframework from the project

### ISSUE THREAD

**Issue by nikhilbhawsar** [adobe/aepsdk-analytics-ios#58]
I am trying to use this lib using swift package manager. When I am performing `@import AEPAnalytics;` it is showing us following error
`Ignoring file /<PROJECT_DERIVED_DATA_DIRECTORY>/Build/Products/Debug.Stage-iphonesimulator/AEPAnalytics.o, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-arm64`

Later instead of importing whole lib via SPM, I tried create xcframework as mentioned in the document using command 
`make archive`

but that command is also exiting with some error
`** ARCHIVE FAILED **
make: *** [archive] Error 65`

### Expected Behaviour
While importing the project, it should also run with architecture x86_64

### Actual Behaviour
Build is failing with architecture error.

### Reproduce Scenario (including but not limited to)
N/A
#### Steps to Reproduce
N/A
#### Platform and Version
N/A
#### Sample Code that illustrates the problem
N/A
#### Logs taken while reproducing problem
N/A

**Comment by nikhilbhawsar** [comment]
Hello @kunal30xi, the above-mentioned issue should have been fixed with PR - #57.
Can you please sync with the latest and try again?

**Comment by kunal30xi** [comment]
Hi @nikhilbhawsar . Building against `main` does indeed fix the issue. Do you have an ETA on when the fix is expected to be `released` and `tagged`. It's our preference to pin our builds against `released` versions of libraries.

**Comment by nikhilbhawsar** [comment]
@addb can provide more info here.

**Comment by addb** [comment]
Hi @nikhilbhawsar, @kunal30xi 

The expectation is to use the latest main branch for generating the binaries. We did not have any code changes so there has not been any release after the build changes. We will look into this SPM issue and make the release if necessary or bundle it with any changes going out. I will post an update here.

Thanks,
Arjun

**Comment by addb** [comment]
Hi @nikhilbhawsar, @kunal30xi  I just tested the SPM with a Swift and Obj-C project. Was able to get the SDK running without any errors. What version rules are you using for SPM packages?

**Comment by addb** [comment]
I will close this for now. If you guys still see the issue let us know.
