### ISSUE TITLE
Can't set port in server config value on iOS

### ISSUE THREAD

**Issue by waynemyoung** [adobe/aepsdk-analytics-ios#67]
### Expected Behaviour

Setting a server config value in the format `host:port` should send analytics to that host on that port.

### Actual Behaviour

The request goes to `host%3aport`, with the port information url encoded into the host.

#### Steps to Reproduce

Set a server config value in the format `host:port`.
Send Analytics track state or action.

#### Platform and Version

iOS 15. Swift Package AEPAnalytics 3.0.3

In the file `URL+Analytics.swift`, line 30, the port urlComponent is not set. state.host should be split on `:` and port component set separately.

```swift
        var urlComponent = URLComponents()
        urlComponent.scheme = "https"
        urlComponent.host = state.host
        urlComponent.path = "/b/ss/\(state.rsids ?? "")/\(getAnalyticsResponseType(state: state))/\(version)/s"```

**Comment by emdobrin** [comment]
Hi @waynemyoung,

The tracking server (analytics.server configuration field) is intended to be used for the tracking domain for Adobe Analytics requests - more details https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics#tracking-server
Can you provide more details on your use-case and why a port is required?

Thanks,
Emilia Dobrin

**Comment by waynemyoung** [comment]
Hi @emdobrin 

We have apps for both iOS and Android. In our non production environments we send analytics to a custom service that logs the requests. These can then be queried for testing/debugging purposes.

The Android SDK is able to handle the `host:port` format just fine but the iOS SDK behaves as described.

Thanks,

Wayne

**Comment by waynemyoung** [comment]
.....additionally, this has only become an issue since migrating from the pod to the swift package.

**Comment by emdobrin** [comment]
Hi @waynemyoung,

Current implementation seems correct for the tracking domain definition. For testing purposes I see few options for you:
1. Fork this repo and modify the code as needed for your test case.
2. If you are not already doing this, take a look at testing Analytics with Adobe Assurance 
      - [Configuration steps for Assurance extension](https://aep-sdks.gitbook.io/docs/foundation-extensions/adobe-experience-platform-assurance)
      - More details about the [Adobe Analytics view in Adobe Assurance](https://aep-sdks.gitbook.io/docs/beta/project-griffon/using-project-griffon/adobe-analytics-and-project-griffon)
3. Alternatively, you could use a Mock NetworkService and overwrite the default Network Service in your tests, then query the requests received for assertions - [docs](https://github.com/adobe/aepsdk-core-ios/blob/main/Documentation/Services/README.md#overriding-a-service).

Emilia

**Comment by addb** [comment]
@waynemyoung If you have any more questions, feel free to open a ticket with our [customer support team](https://experienceleague.adobe.com/?support-solution=General#support)
