### ISSUE TITLE
Documentation link resolves to 404

### ISSUE THREAD

**Issue by ppaugh** [adobe/aepsdk-analytics-ios#75]
### Expected Behaviour
The Documentation link (https://github.com/adobe/aepsdk-analytics-ios/blob/main/Documentation/README.md) should resolve to a valid page containing documentation

### Actual Behaviour
https://github.com/adobe/aepsdk-analytics-ios/blob/main/Documentation/README.md

**Comment by cacheung** [comment]
Thanks for reporting. 
The documentation directory is updated in the Readme.
