### ISSUE TITLE
I have integrated Firebase Messaging feature in my app. When I import these adobe files i.e. when I write 'import AEPCore' or any of these in AppDelegate file. I start getting error . "Cannot assign value of type 'AppDelegate' to type 'MessagingDelegate?" 

### ISSUE THREAD

**Issue by SHIVIVIJ** [adobe/aepsdk-analytics-ios#82]

**Comment by addb** [comment]
Importing AEPCore or AEPAnalytics SDK shouldnt throw this error. The error looks like is coming from your firebase implementation.

**Comment by SHIVIVIJ** [comment]
Hi ,
This issue has been resolved.
I tried
extension AppDelegate: FirebaseMessaging.MessagingDelegate {} instead
of extension
AppDelegate: MessagingDelegate {}

Thanks.
Shivi
