### ISSUE TITLE
ios side MCID— Experience Cloud ID (ECID) value is getting but getThirdPartyId.,getTntId are getting nil values.

### ISSUE THREAD

**Issue by shravanteegala** [adobe/aepsdk-analytics-ios#92]
hi @cacheung ,
MCID— Experience Cloud ID (ECID) value is getting, but getThirdPartyId., getTntId values are getting nil, so where we needs to check adobe side setting those values (configuration file). how can i check those values are configure(set) or not. ?
So Adobe side Where we need to check .

**Comment by cacheung** [comment]
@shravanteegal 
getThirdPartyId value needs to set by the client app.  
Please refer to setThirdPartyId API - https://developer.adobe.com/client-sdks/documentation/adobe-target/api-reference/#setthirdpartyid

getTntID value returns while you configure Target properly and make a successful request to Target and then the response should contain tnt id value.
https://developer.adobe.com/client-sdks/documentation/adobe-target/api-reference/#gettntid

**Comment by shravanteegala** [comment]
@cacheung,
i checked my iOS Console log,.
i'm not set manually ECID,But Experience Cloud ID (ECID) is getting value, , how i get ecid. why we are not getting thirdPartyId , TntId like ecid(ECID).

**Comment by cacheung** [comment]
@shravanteegala 
The ECID is generated by SDK Identity extension automatically when app launches, client doesn't need to set it.
https://developer.adobe.com/client-sdks/documentation/mobile-core/identity/api-reference/#getexperiencecloudid

thirdPartyId is a client id which for user to set for their app.  They need to call the setter to set the value in the client app. (User uses that if they want to create a client id for their app)

tntId is generated from the Target response.  

Both thirdPartyId and tntId are handled in Target Extension.

**Comment by shravanteegala** [comment]
Thank you @cacheung,
so can i generate random values for setting thirdPartyId,tntId. for my client App. ?

**Comment by cacheung** [comment]
@shravanteegala 
Yes, for setThirdPartyId you can use setThirdPartyId API, and set to any string value.
https://developer.adobe.com/client-sdks/documentation/adobe-target/api-reference/#setthirdpartyid

For tntId, you should get it if you setup the target configuration properly.  Do you have target setup properly?
https://developer.adobe.com/client-sdks/documentation/adobe-target/

But there is also a setTntId API to set it in String value.
https://developer.adobe.com/client-sdks/documentation/adobe-target/api-reference/#settntid

**Comment by shravanteegala** [comment]
Thank you @cacheung.

**Comment by cacheung** [comment]
@shravanteegala 
Do you have other question?  Could we close the ticket?

**Comment by shravanteegala** [comment]
sure @cacheung
