### ISSUE TITLE
Does not build using `make archive`

### ISSUE THREAD

**Issue by markph0204** [adobe/aepsdk-analytics-ios#94]
### Expected Behaviour
Make XCFrameworks
### Actual Behaviour
Error:

/Users/markhurley/tmp/adobe/aepsdk-analytics-ios/AEPAnalytics/Sources/AnalyticsState.swift:13:8: error: no such module 'AEPCore'
import AEPCore
       ^

warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'AEPAnalytics' from project 'AEPAnalytics')
** ARCHIVE FAILED **
#### Steps to Reproduce
Use `make archive` to build XCFrameworks
#### Platform and Version
Xcode 14.3; tested on macOS Ventura 13.3.1 arm64 and separately x86 Intel

**Comment by markph0204** [comment]
Sure - here you are, command `make archive | tee build.log`

[build.log](https://github.com/adobe/aepsdk-analytics-ios/files/11399124/build.log)

**Comment by cdhoffmann** [comment]
@markph0204 Thanks. Just to make sure, you haven't modified the AEPAnalytics project in any way? Make sure you are on the main branch, without changes. Could you also try clearing derived data?

**Comment by markph0204** [comment]
Correct. I use a command to zero/reset everything back to original state
‘gpristine’ from ohmyzsh.  I keep my derivedData in proj folders always to
wipe for this reason.

**Comment by cdhoffmann** [comment]
@markph0204 Thanks. It seems like the log you posted gets cut off. Could you run a `make clean` and then `make archive` again and send the full logs.

**Comment by markph0204** [comment]
Sure ... I took this approach...

```bash
git clone git@github.com:adobe/aepsdk-analytics-ios.git && cd aepsdk-analytics-ios && make archive > build.log 2>&1
```

build log attached
[build.log](https://github.com/adobe/aepsdk-analytics-ios/files/11400368/build.log)

**Comment by markph0204** [comment]
Same issue here as other reported.  tvOS was not installed in either workstation -- problem solved, tested on x86 only.
