### ISSUE TITLE
Add xcframeworks to release.

### ISSUE THREAD

**Issue by kunal30xi** [adobe/aepsdk-analytics-ios#99]
Now that aepsdk-core-ios and aepsdk-assurance-ios are both making XCframeworks available with their latest release (4.0.0), can we ensure that XCFramework binaries are released for analytics as well?

**Comment by addb** [comment]
Hey @kunal30xi, We will be releasing Analytics 4.0.0 with the XCFrameworks  really soon (this week).

Thanks,
Arjun

**Comment by addb** [comment]
[AEPAnalytics 4.0.0](https://github.com/adobe/aepsdk-analytics-ios/releases/tag/4.0.0) is now available.
